`timescale 1ns/1ps

module async_fifo_tb;

reg wr_clk;
reg rd_clk;
reg rst;

reg wr_en;
reg rd_en;

reg [7:0] data_in;

wire [7:0] data_out;
wire full;
wire empty;

async_fifo dut(
    .wr_clk(wr_clk),
    .rd_clk(rd_clk),
    .rst(rst),

    .wr_en(wr_en),
    .rd_en(rd_en),

    .data_in(data_in),
    .data_out(data_out),

    .full(full),
    .empty(empty)
);

always #5 wr_clk = ~wr_clk;
always #8 rd_clk = ~rd_clk;

initial begin
    $dumpfile("async_fifo.vcd");
    $dumpvars(0, async_fifo_tb);

    wr_clk = 0;
    rd_clk = 0;

    rst = 1;
    wr_en = 0;
    rd_en = 0;
    data_in = 0;

    #20 rst = 0;

    #200;

    $finish;
end

endmodule